// <auto-generated />
using System;
using JobFinder.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobFinder.Migrations
{
    [DbContext(typeof(JobFinderContext))]
    [Migration("20230430122735_secondMigration")]
    partial class secondMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("JobFinder.JobListings.JobListing", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Company")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DatePosted")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("JobListings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Company = "Google",
                            DatePosted = new DateTime(2023, 4, 30, 14, 27, 34, 986, DateTimeKind.Local).AddTicks(9704),
                            Description = "C# Programmer",
                            Location = "Johannesburg, South Africa",
                            Title = "C#Developer"
                        },
                        new
                        {
                            Id = 2,
                            Company = "Amazon",
                            DatePosted = new DateTime(2023, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Node Developer",
                            Location = "Cape Town, South Africa",
                            Title = "JavaScript/TypeScript Developer"
                        },
                        new
                        {
                            Id = 3,
                            Company = "Microsoft",
                            DatePosted = new DateTime(2022, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Data Science Developer",
                            Location = "Durban, South Africa",
                            Title = "Python Developer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
